### ISSUE TITLE
Integration jsmediatags and meteor

### ISSUE THREAD

**Issue by oogre** [aadsm/jsmediatags#3]
Hello,
I'm trying to integrate this lib to a Meteor project.
To do this I added meteorhacks package : 
`meteor add meteorhacks:npm`
Then in the packages.json I wrote :
`{
	"jsmediatags": "3.0.0"
}`
And then I used jsmediatags like that : 
```
var jsmediatags = Meteor.npmRequire('jsmediatags');
jsmediatags.read(url, {
	onSuccess: function(tag) {
		var tags = tag.tags;
		console.log(tags);
	}
});
```
And it crash like that : 
```
I20160129-15:39:48.395(1)? Exception while invoking method 'podcastAdd' SyntaxError: Use of const in strict mode.
I20160129-15:39:48.395(1)?     at Module._compile (module.js:439:25)
I20160129-15:39:48.395(1)?     at Object.Module._extensions..js (module.js:474:10)
I20160129-15:39:48.396(1)?     at Module.load (module.js:356:32)
I20160129-15:39:48.396(1)?     at Function.Module._load (module.js:312:12)
I20160129-15:39:48.396(1)?     at Module.require (module.js:364:17)
I20160129-15:39:48.396(1)?     at require (module.js:380:17)
I20160129-15:39:48.396(1)?     at Object.Npm.require (/Users/ogre/Work/6102/ogre/from.brussels/.meteor/local/build/programs/server/boot.js:162:18)
I20160129-15:39:48.396(1)?     at Object.Meteor.npmRequire (packages/npm-container/index.js:2:1)
I20160129-15:39:48.396(1)?     at [object Object].Meteor.methods.podcastAdd (lib/methods/podcast.js:14:29)
I20160129-15:39:48.396(1)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
W20160129-15:39:48.394(1)? (STDERR)
W20160129-15:39:48.395(1)? (STDERR) /Users/ogre/Work/6102/ogre/from.brussels/.meteor/local/isopacks/npm-container/npm/node_modules/jsmediatags/build/jsmediatags.js:4
W20160129-15:39:48.395(1)? (STDERR) const MediaFileReader = require("./MediaFileReader");
W20160129-15:39:48.395(1)? (STDERR) ^^^^^
```
Any idea to solve it properly ?

**Comment by aadsm** [comment]
I see, it looks like my babel configuration isn't compiling `const` into `var`.
I'll fix this tomorrow, thanks for reporting!

**Comment by oogre** [comment]
Yeah Great!

**Comment by aadsm** [comment]
I've just published a new version on npm (`3.0.1`) with this fix.
Btw, which node version are you using?

**Comment by oogre** [comment]
I'm using Node v4.2.6

**Comment by oogre** [comment]
It remains something strange : 
I20160201-12:14:15.073(1)? [SyntaxError: Unexpected reserved word]
W20160201-12:14:15.072(1)? (STDERR)
W20160201-12:14:15.073(1)? (STDERR) /Users/ogre/Work/6102/ogre/from.brussels/packages/npm-container/.npm/package/node_modules/jsmediatags/build/jsmediatags.js:20
W20160201-12:14:15.073(1)? (STDERR) class Reader {
W20160201-12:14:15.073(1)? (STDERR) ^^^^^

**Comment by aadsm** [comment]
I have version v4.2.3 and it works as expected, node supports ES6 classes natively starting from v4.
It also supports const actually, I thought you had an older version of node that didn't support it, but all v4 do, so that was not the issue.

I've googled about this and it seems that meteor doesn't use the node version that is installed in your system, it uses its own, and it's not v4.0.
There is a specific thread on meteor github issues regarding this issue: https://github.com/meteor/meteor/issues/5124.

I would like to avoid compiling everything down to ES5 for performance reasons. Here's what you can do in the meanwhile, at least for development (I don't know how you push to production).
- Clone the repo with `git clone https://github.com/aadsm/jsmediatags.git` and `npm link` in that directory.
- Update the contents of `.babelrc` with https://gist.github.com/aadsm/cd2c5aff9929bdc95b55.
- Run `npm install`.
- Run `npm run build`.
- Go to your own project and run `npm link jsmediatags`, this will make node use the one linked in the first step instead of the one published in npm.
